# Generated by Django 4.0 on 2021-12-20 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5)]),
        ),
    ]
