# Generated by Django 4.0 on 2021-12-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('books', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='add',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
