# Generated by Django 4.0 on 2021-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_country_author_publishing_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publishing_countries',
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_countries',
            field=models.ManyToManyField(to='books.Country'),
        ),
    ]
