# Generated by Django 4.0 on 2021-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_author_publishing_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_countries',
            field=models.ManyToManyField(null=True, to='books.Country'),
        ),
    ]
