# Generated by Django 4.0 on 2021-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
