# Generated by Django 4.0 on 2021-12-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilemodel_age_profilemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='user_img',
            field=models.FileField(upload_to='profiles/static/profiles/images'),
        ),
    ]
